version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  main:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    command: python main.py
  db:
    image: mongo:6.0.6
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
